name = "memory-note"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
    { binding = "MEMORY_NOTE", id = "8b7fae40961545f5a439480ed18a32ba", preview_id = "89e03c9ccb1c48a68baf22d75f3d06fb" }
]
compatibility_date = "2021-09-26"
